### PR TITLE
Fix/501

### LINKED ISSUE #501: Replace X on ErrorBox with Caution Icon - users think the X icon is a close button to X out the error

### PR DESCRIPTION
**Pull request by Schwartz10**
@navFooh a user thought t he "x" icon was a button to click to close the error. this addresses that issue, and in the process, i tried to clean up some of the Color ts typing

### CODE REVIEW

File: src/components/Icons/index.tsx [hunk 1]
```diff
@@ -1071,31 +1071,29 @@ export const IconWarn = () => (
...
+
+IconCaution.propTypes = {
+  stroke: string
+}
+
+IconCaution.defaultProps = {
+  stroke: Colors.YELLOW_DARK
+}
+
+export const IconWarn = () => <IconCaution />
```
Comment (Schwartz10) [inline src/components/Icons/index.tsx:1094]: To remain backwards compat

**Review by navFooh — APPROVED** [review]
