### PR TITLE
Fix AddressLink line height and create Safe ID input

### LINKED ISSUE #266: lineHeight of Address rows in Admin safe is off?
image

Does this look misaligned to you @navFooh ?

### PR DESCRIPTION
**Pull request by navFooh**
+ enable auto-completion for InputV2
+ make Address input truncation optional

### CODE REVIEW

File: src/components/Transaction/Loading.tsx [hunk 1]
```diff
@@ -1,30 +1,22 @@
...
       <p>{description}</p>
-    </LoadingBox>
+    </StandardBox>
   )
 }
 
+export interface TransactionLoadingProps {
+  description?: string
+}
+
```
Comment (navFooh) [inline src/components/Transaction/Loading.tsx:19]: @Schwartz10 I think it's a nice convention to always define TypeScript and React props below the Component

File: src/components/Transaction/Loading.tsx [hunk 2]
```diff
@@ -1,30 +1,22 @@
...
 import LoaderGlyph from '../LoaderGlyph'
-import { space } from '../theme'
-
-const LoadingBox = styled(StandardBox)`
-  > *:first-child {
-    margin-right: ${space()};
-    text-align: left;
-    align-self: center;
-  }
-`
```
Comment (navFooh) [inline src/components/Transaction/Loading.tsx:13]: @Schwartz10 The `margin-right` made the loading icon a bit off-centered, `align-self` only applies to flex or grid children, which this is not. I moved the `text-align` to the `LoaderGlyph` itself since it makes more sense there when it relies on it.

File: src/components/Transaction/State.tsx [hunk 3]
```diff
@@ -5,18 +5,13 @@ import {
...
 } from '../../customPropTypes'
 import { TransactionConfirm } from './Confirm'
 import { TransactionLoading } from './Loading'
 
-export enum TxState {
-  FillingForm,
-  LoadingTxDetails,
-  AwaitingConfirmation,
-  MPoolPushing
-}
```
Comment (navFooh) [inline src/components/Transaction/State.tsx:18]: @Schwartz10 Moved this to our `customPropTypes` file, as it's nicer to reuse it across components that way

File: src/components/InputV2/Address.tsx [hunk 4]
```diff
@@ -13,16 +13,20 @@ export const AddressInput = ({
...
-  const error = useMemo<string>(
-    () => (validateAddressString(value) ? '' : 'Needs to be a valid address'),
-    [value]
-  )
+  const error = useMemo<string>(() => {
+    if (!validateAddressString(value)) return 'Needs to be a valid address'
+    if (msig && value[1] !== '0' && value[1] !== '2')
+      return 'Second character must be 0 or 2'
+    return ''
+  }, [value, msig])
```
Comment (Schwartz10) [inline src/components/InputV2/Address.tsx]: Let's rename `msig` to `actor` - actor IDs are either `f0` (id) or `f2` (robust)

**Review by Schwartz10 — CHANGES_REQUESTED** [review]
Only 1 easy name change her eand this can get merged

File: src/components/InputV2/Address.tsx (hunk 4 above)
Comment (navFooh) [reply src/components/InputV2/Address.tsx]: done!
